#spring:
#  redis:
#    cluster:
#      ports:
#        - 8001
#        - 8002
#        - 8003
#        - 8004
#        - 8005
#        - 8006
#        - 8007
#        - 8008
#        - 8009
#        - 8010
#      hosts:
#        - 127.0.0.1
#        - 127.0.0.1
#        - 127.0.0.1
#        - 127.0.0.1
#        - 127.0.0.1
#        - 127.0.0.1
#        - 127.0.0.1
#        - 127.0.0.1
#        - 127.0.0.1
#        - 127.0.0.1
#      password: 123@456
#      poolConfig:
#        max-total: 10
#        max-idle: 10
#        max-wait-millis: -1
#        min-idle: 0

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.xuan.entity  # 注意：对应实体类的路径
  configuration:
    #org.apache.ibatis.logging.stdout.StdOutImpl 控制台打印sql语句方便调试sql语句执行错误
    #org.apache.ibatis.logging.log4j2.Log4j2Impl:这个不在控制台打印查询结果,但是在log4j中打印
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    mapUnderscoreToCamelCase: true # 开启驼峰命名转换法

logging:
  config: classpath:log4j2.xml
  level:
    org.manage.mapper: trace